import Head from 'next/head'
import { Layout, theme, Row, Col, Button, Form, Select, DatePicker, Image } from 'antd';
import Banner from './components/shared/Banner';
import Navbar from './components/shared/Navbar';
import FooterBar from './components/shared/FooterBar';
import ArticleHome from './components/ArticleHome';
const { Content } = Layout;


export default function Home() {
  const {
    token: { colorBgContainer },
  } = theme.useToken();
  return (
    <>
      <Head>
        <title>Welcome to ...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout className="layout">
          <Navbar />
          <Content>
            <Banner />
            <HomeSearchPanel />
            {/* <ArticleHome /> */}
          </Content>
          <FooterBar />
        </Layout>
      </main>
    </>
  )
}


function HomeSearchPanel() {

  const handleChange = (value) => {
    console.log(`selected ${value}`);
  };

  return (
    <>
      <section className='section bg-white'>
        <div className='container-lg'>
          <div className='search-map'>
            <Form layout={'vertical'}>
              <Row>
                <Col sm={20} xs={24}>
                  <Row gutter={[24, 0]}>
                    <Col md={6} sm={12} xs={24}>
                      <Form.Item label="Category">
                        <Select size="large"
                          defaultValue="lucy"
                          onChange={handleChange}
                          options={[
                            {
                              value: 'jack',
                              label: 'Jack',
                            },
                            {
                              value: 'lucy',
                              label: 'Lucy',
                            },
                            {
                              value: 'Yiminghe',
                              label: 'yiminghe',
                            },
                            {
                              value: 'disabled',
                              label: 'Disabled',
                              disabled: true,
                            },
                          ]}
                        />
                      </Form.Item>
                    </Col>
                    <Col md={6} sm={12} xs={24}>
                      <Form.Item label="Sub Category">
                        <Select size="large"
                          defaultValue="lucy"
                          
                          onChange={handleChange}
                          options={[
                            {
                              value: 'jack',
                              label: 'Jack',
                            },
                            {
                              value: 'lucy',
                              label: 'Lucy',
                            },
                            {
                              value: 'Yiminghe',
                              label: 'yiminghe',
                            },
                            {
                              value: 'disabled',
                              label: 'Disabled',
                              disabled: true,
                            },
                          ]}
                        />
                      </Form.Item>
                    </Col>

                    <Col md={6} sm={12} xs={24}>
                      <Form.Item label="Keyword">
                        <Select size="large"
                          defaultValue="lucy"
                         
                          onChange={handleChange}
                          options={[
                            {
                              value: 'jack',
                              label: 'Jack',
                            },
                            {
                              value: 'lucy',
                              label: 'Lucy',
                            },
                            {
                              value: 'Yiminghe',
                              label: 'yiminghe',
                            },
                            {
                              value: 'disabled',
                              label: 'Disabled',
                              disabled: true,
                            },
                          ]}
                        />
                      </Form.Item>
                    </Col>
                    <Col md={6} sm={12} xs={24}>
                      <Form.Item label="Time Range" >
                        <DatePicker size="large" width="100%" />
                      </Form.Item>
                    </Col>

                  </Row>
                </Col>
                <Col sm={4} xs={24}>
                  <Form.Item label="">
                    <Button type='default' size="large">Search</Button>
                  </Form.Item>
                </Col>
              </Row>
            </Form>
          </div>

          <Row>
            <Col span={24}>
              <Image src='../images/map.png' preview={false} />
            </Col>
          </Row>
          <Row>
            <Col span={24}><h3 className='map-title'>Content Heat Map</h3></Col>
          </Row>

        </div>

      </section>
    </>
  )
}

