import Head from 'next/head'

import { Breadcrumb, Pagination, Layout, Menu, Radio, theme, Row, Col, Input, Checkbox, Button, Form, Select, DatePicker, Dropdown, Image } from 'antd';
import { HeartOutlined, FacebookFilled, UserOutlined, DownOutlined, EllipsisOutlined, VerticalAlignBottomOutlined, ShareAltOutlined, TwitterSquareFilled, InstagramOutlined, ArrowRightOutlined, ArrowLeftOutlined } from '@ant-design/icons';
import Banner from './components/shared/Banner';
// import Footer from './components/shared/Footer';

const { Header, Content, Footer } = Layout;

export default function Login() {
    const {
        token: { colorBgContainer },
    } = theme.useToken();
    return (
        <>
            <Head>
                <title>Welcome to ...</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Layout className="layout">
                    <Header>
                        <div className="container-lg">
                            <Row gutter={24}>
                                <Col span={2} xs={24} xl={2}><Image src="../images/logo.png" /></Col>
                                <Col span={16} className="menu"> <Menu
                                    theme='light'
                                    mode="horizontal"
                                    defaultSelectedKeys={['1']}>
                                    <Menu.Item key="1" >
                                        Home
                                    </Menu.Item>
                                    <Menu.Item key="2" >
                                        News
                                    </Menu.Item>
                                    <Menu.Item key="3" >
                                        Library
                                    </Menu.Item>
                                    <Menu.Item key="4" >
                                        Target serach
                                    </Menu.Item>
                                    <Menu.Item key="5" >
                                        Enforcement Actions
                                    </Menu.Item>
                                    <Menu.Item key="6" >
                                        Raise Ticket
                                    </Menu.Item>
                                </Menu></Col>
                                <Col span={4}>
                                    <Input size='large' />

                                </Col>
                                <Col span={2}>

                                    <Button type="primary" size='large'>My Notes</Button>
                                </Col>
                            </Row>
                        </div>
                    </Header>
                    <Content
                        className="">
                        <section className='section' style={{ background: '#D0D5DD' }}>
                            <div className='container-lg'>
                                <div className='login-box'>

                                    <h3 className='heading'>Sign In</h3>
                                    <Form layout="vertical">
                                        <Form.Item label="Email">
                                            <Input placeholder="for e.g abc123@gmail.com" size='large' />
                                        </Form.Item>
                                        <Form.Item label="Password">
                                        <Input placeholder="for e.g abc123@gmail.com" size='large' />
                                            
                                        </Form.Item>
                                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' }}>
                                            <div><Checkbox>Keep me signed in.</Checkbox></div>
                                            <div>Forgot Password?</div>
                                        </div>
                                        <Form.Item >
                                            <Button type="primary" size='large' style={{ width: '100%' }}>Sign In</Button>
                                        </Form.Item>

                                    </Form>
                                    <div>Don’t have an Account? <a href="">Create New Account</a></div>
                                </div>
                            </div>
                        </section>
                    </Content>
                    <Footer>
                        <section className='bg-white'>
                            <div className="container-lg">
                                <Row>
                                    <Col span={11}>
                                        <div style={{ width: '90%' }}>
                                            <div style={{ marginBottom: '30px' }}><h3>About Contoso</h3></div>
                                            <div style={{ marginBottom: '30px', fontSize: '14px', color: '#52525B', lineHeight: '20px' }}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dictum aliquet accumsan porta lectus ridiculus in mattis. Netus sodales in volutpat ullamcorper amet adipiscing fermentum.</div>
                                            <div style={{ display: 'flex', justifyContent: 'space-between', width: '100px', fontSize: '24px' }}>
                                                <FacebookFilled />
                                                <TwitterSquareFilled />
                                                <InstagramOutlined />
                                            </div>
                                        </div>
                                    </Col>
                                    <Col span={13}>
                                        <Row className='mega-menu'>
                                            <Col span={6}>
                                                <h3>Learn</h3>
                                                <ul>
                                                    <li><a href="javascript:">All Retail Products</a></li>
                                                    <li><a href="javascript:">Home</a></li>
                                                    <li><a href="javascript:">Commercial </a>        </li>
                                                    <li><a href="javascript:">Distributors</a></li>
                                                </ul>
                                            </Col>
                                            <Col span={6}>
                                                <h3>Contoso Store</h3>
                                                <ul>
                                                    <li><a href="javascript:">View Account
                                                    </a></li>
                                                    <li><a href="javascript:">Order Tracking
                                                    </a></li>
                                                    <li><a href="javascript:">Returns
                                                    </a>         </li>
                                                    <li><a href="javascript:">Sales & Support</a></li>
                                                </ul></Col>
                                            <Col span={6}>
                                                <h3>Downloads</h3>
                                                <ul>
                                                    <li><a href="javascript:">Product Manuals</a></li>
                                                    <li><a href="javascript:">White Papers</a></li>
                                                    <li><a href="javascript:">Contoso Apps</a></li>

                                                </ul>
                                            </Col>
                                            <Col span={6}>
                                                <h3>Company</h3>
                                                <ul>
                                                    <li><a href="javascript:">Careers at Contoso</a></li>
                                                    <li><a href="javascript:">About Contoso</a></li>
                                                    <li><a href="javascript:">Company News</a></li>
                                                    <li><a href="javascript:">Site Map</a></li>

                                                </ul></Col>

                                        </Row>
                                    </Col>
                                </Row>
                            </div>
                        </section>

                    </Footer>
                    <section className='bg-white'>
                        <div className="container-lg">
                            <ul className='footer-menu'>
                                <li><a href="javascript:"> Contact</a></li>
                                <li><a href="javascript:"> Privacy policy</a></li>
                                <li><a href="javascript:"> Sitemap</a></li>
                                <li><a href="javascript:"> Terms of Use</a></li>
                            </ul>
                        </div>
                    </section>
                </Layout>
            </main>
        </>
    )
}


