import Head from 'next/head'
import { Breadcrumb, Pagination, Layout, Menu, theme, Collapse, Row, Col, Input, Button, Form, Select, DatePicker, Dropdown, Image } from 'antd';
import { HeartOutlined, FacebookFilled, UserOutlined, DownOutlined, EllipsisOutlined, VerticalAlignBottomOutlined, ShareAltOutlined, TwitterSquareFilled, InstagramOutlined, ArrowRightOutlined, ArrowLeftOutlined } from '@ant-design/icons';
const { Header, Content, Footer } = Layout;
import Banner from './components/shared/Banner';
// import Footer from './components/shared/Footer';
const { Panel } = Collapse;

export default function Home() {
  const {
    token: { colorBgContainer },
  } = theme.useToken();
  return (
    <>
      <Head>
        <title>Welcome to ...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout className="layout">
          <Header>
            <div className="container-lg">
              <Row gutter={24}>
                <Col span={2}><Image src="../images/logo.png" /></Col>
                <Col span={16} className="menu"> <Menu
                  theme='light'
                  mode="horizontal"
                  defaultSelectedKeys={['1']}


                >
                  <Menu.Item key="1" >
                    Home
                  </Menu.Item>
                  <Menu.Item key="2" >
                    News
                  </Menu.Item>
                  <Menu.Item key="3" >
                    Library
                  </Menu.Item>
                  <Menu.Item key="4" >
                    Target serach
                  </Menu.Item>
                  <Menu.Item key="5" >
                    Enforcement Actions
                  </Menu.Item>
                  <Menu.Item key="6" >
                    Raise Ticket
                  </Menu.Item>
                </Menu></Col>
                <Col span={4}>
                  <Input size='large' />

                </Col>
                <Col span={2}>

                  <Button type="primary" size='large'>My Notes</Button>
                </Col>
              </Row>
            </div>
          </Header>
          <Content
            className="">

            <section className='section bg-white'>
              <div className='container-lg'>
                <HomeSearchPanel />
              </div>
            </section>
            {/* <HomeSearchPanel /> */}
            <section className='section bg-white'>
              <div className='container-lg'>
                <Row>
                  <Col span={24}><h3 className='title'>Search Result</h3></Col>
                </Row>
                <Collapse defaultActiveKey={['1']}>
                  <Panel header="General Information" key="1">
                    <p>Act on Evaluation e</p>
                    <p>Act on Evaluation e</p>
                    <p>Act on Evaluation e</p>
                  </Panel>
                  <Panel header="Chemical Hazard and Risk Information" key="2">
                    <p>sss</p>
                  </Panel>
                  <Panel header="Test Data and Reports" key="3">
                    <p>11</p>
                  </Panel>
                </Collapse>
              </div>
            </section>
            <section className='section'>
              <div className='container-lg'>
                <div style={{ background: '#272B30;', borderRadius: '12px', padding: '31px 36px' }}>
                  <Row>
                    <Col span={14}>
                      <h4>
                        Newsletter
                      </h4>
                      <span>Get notified when new content is available</span>
                    </Col>
                    <Col span={10}>
                      <Input placeholder='Enter your email' size='large'/>
                      <Button>Subcribe</Button>
                    </Col>
                  </Row>
                </div>

              </div>
            </section>
          </Content>
          <Footer>
            <section className='bg-white'>
              <div className="container-lg">
                <Row>
                  <Col span={11}>
                    <div style={{ width: '90%' }}>
                      <div style={{ marginBottom: '30px' }}><h3>About Contoso</h3></div>
                      <div style={{ marginBottom: '30px', fontSize: '14px', color: '#52525B', lineHeight: '20px' }}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dictum aliquet accumsan porta lectus ridiculus in mattis. Netus sodales in volutpat ullamcorper amet adipiscing fermentum.</div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', width: '100px', fontSize: '24px' }}>
                        <FacebookFilled />
                        <TwitterSquareFilled />
                        <InstagramOutlined />
                      </div>
                    </div>
                  </Col>
                  <Col span={13}>
                    <Row className='mega-menu'>
                      <Col span={6}>
                        <h3>Learn</h3>
                        <ul>
                          <li><a href="javascript:">All Retail Products</a></li>
                          <li><a href="javascript:">Home</a></li>
                          <li><a href="javascript:">Commercial </a>        </li>
                          <li><a href="javascript:">Distributors</a></li>
                        </ul>
                      </Col>
                      <Col span={6}>
                        <h3>Contoso Store</h3>
                        <ul>
                          <li><a href="javascript:">View Account
                          </a></li>
                          <li><a href="javascript:">Order Tracking
                          </a></li>
                          <li><a href="javascript:">Returns
                          </a>         </li>
                          <li><a href="javascript:">Sales & Support</a></li>
                        </ul></Col>
                      <Col span={6}>
                        <h3>Downloads</h3>
                        <ul>
                          <li><a href="javascript:">Product Manuals</a></li>
                          <li><a href="javascript:">White Papers</a></li>
                          <li><a href="javascript:">Contoso Apps</a></li>

                        </ul>
                      </Col>
                      <Col span={6}>
                        <h3>Company</h3>
                        <ul>
                          <li><a href="javascript:">Careers at Contoso</a></li>
                          <li><a href="javascript:">About Contoso</a></li>
                          <li><a href="javascript:">Company News</a></li>
                          <li><a href="javascript:">Site Map</a></li>

                        </ul></Col>
                    </Row>
                  </Col>
                </Row>
              </div>
            </section>

          </Footer>
          <section className='bg-white'>
            <div className="container-lg">
              <ul className='footer-menu'>
                <li><a href="javascript:"> Contact</a></li>
                <li><a href="javascript:"> Privacy policy</a></li>
                <li><a href="javascript:"> Sitemap</a></li>
                <li><a href="javascript:"> Terms of Use</a></li>
              </ul>
            </div>
          </section>
        </Layout>
      </main>
    </>
  )
}


function HomeSearchPanel() {

  const handleChange = (value) => {
    console.log(`selected ${value}`);
  };
  return (
    <>
      <div className='search-map'>
        <div>
          <Form.Item label="Search">
            <Input placeholder='Search By Products' />
          </Form.Item>
        </div>

        <div>
          <Form.Item label="Time Range">
            <DatePicker />
          </Form.Item>
        </div>

        <div>
          <Form.Item label="">
            <Button type='default' size="large">Search</Button>
          </Form.Item>
        </div>
      </div>

      <Row>
        <Col span={24}>
          <img src='../images/map.png' />
        </Col>
      </Row>
      <Row>
        <Col span={24}><h3 className='map-title'>Enforcement Report Heat Map</h3></Col>
      </Row>
    </>
  )
}

function ArticleBox() {

  const handleButtonClick = (e) => {
    message.info('Click on left button.');
    console.log('click left button', e);
  };
  const handleMenuClick = (e) => {
    message.info('Click on menu item.');
    console.log('click', e);
  };
  const items = [
    {
      label: '1st menu item',
      key: '1',
      icon: <UserOutlined />,
    },
    {
      label: '2nd menu item',
      key: '2',
      icon: <UserOutlined />,
    },
    {
      label: '3rd menu item',
      key: '3',
      icon: <UserOutlined />,
      danger: true,
    },
    {
      label: '4rd menu item',
      key: '4',
      icon: <UserOutlined />,
      danger: true,
      disabled: true,
    },
  ];
  const menuProps = {
    items,
    onClick: handleMenuClick,
  };

  return (
    <div className='article-box'>
      <div className='img-box'>
        <Image
          width="100%"
          src="../images/article01.png"
        />

      </div>
      <div className='article-date-time'>
        <div> Microsoft iot</div>
        <div> 23 Jan 2022</div>
      </div>
      <div className='title'>Product and service innovation starts in the field</div>
      <div className='desc'>Your search did not match any vendors. Please try again or create add a new vendor.</div>
      <div className='actions'>
        <div><HeartOutlined />
          <ShareAltOutlined />
          <VerticalAlignBottomOutlined />
        </div>
        <div>
          <Dropdown
            menu={{
              items,
            }}
          >
            <a onClick={(e) => e.preventDefault()}>


              <EllipsisOutlined />

            </a>
          </Dropdown>
        </div>

      </div>
    </div>
  )
}